### ISSUE TITLE
I need help deleting the fpsunlocker

### ISSUE THREAD

**Issue by PleaseHelpMe-png** [axstin/rbxfpsunlocker#103]
I've tried deleting all the files i could and its still connecting i dont wanna get banned but i just wanted to see how to use it. I opened the exploit and it connected and i tried getting rid of it like reinstalling roblox and pzazz but its still connecting please help me remove it

**Comment by mxdanger** [comment]
It's not an exploit what so ever and its impossible to get banned for using it. The software is contained in a .exe if you want to delete it then delete the .exe and remove it from your startup apps. Just wondering since you seem to be very young, what refresh rate is your monitor? I'm guessing its 60hz and you don't understand that rbxfpsunlocker is for changing your FPS cap.
