### ISSUE TITLE
Why cant  they boost fps and uncap 

### ISSUE THREAD

**Issue by popularboy7Gaiming** [axstin/rbxfpsunlocker#115]
wheni got onto hardsoftware games like strucid and island royale it just doesent work how come my friend thats on acer got over 300 fps and im stuck with 23 fps maximum this is just a wase of time nobody will install such a scam bc its a waste of time and storage easy software games go to 90 fps but i dont like them bc there is no action in them but the action games have detail and required a more expensive pc like imac and macbook or alienwares everyone who goes to issues know this is what is causing problems hurry up and please uprage fps unlockers for acer i wont just spend money on a higher ranked pc if i already got 1one working all i want is roblox to stop freaking lagging

**Comment by CelestiusBlitz** [comment]
The point of the program is not to _increase_ your FPS, but rather unlock it so your FPS is fluid and can go above the cap of 60, which is what it is normally. 

The IMac and Macbook series are not comparable to the Alienware hardware due to their components. The only way to fix your issue is to get a better computer.
