### ISSUE TITLE
The FPS Unlocker didn't go up more that 60

### ISSUE THREAD

**Issue by Jasonsamlest** [axstin/rbxfpsunlocker#1693]
I tried a couple of times to restart the app and computer. I didn't work at all. But sometimes it goes up when I open another tab. It only works at 30 and 60. Please help. Thank you~

**Comment by CedricJesse** [comment]
The problem is that ur computer has stopped running the file as an administrator. so what u do is this, you go to robloxxfpsunlcoker then right click and click on extract and follow the rest of the instructions. After it has been extracted it will pop up as a red logo similar to that of roblox app. so now click on the extracted file and right click, go to properties and after properties is open click on compatibility and click as run as administrator and click yes for everything. then restart your computer,

**Comment by kaydenplayzroblox** [comment]
@CedricJesse my roblox fps unlocker doesnt work on my laptop even if i put it at 30 fps or 60 fps, i only get 13/12 fps pls help

**Comment by CedricJesse** [comment]
listen to my instructions ontop

**Comment by CedricJesse** [comment]
right click fps unlocker and extract it. then run the file as administrator and then restart your computer

**Comment by Jasonsamlest** [comment]
Thanks, @CedricJesse for solving this problem :D
