### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by konig123YT** [axstin/rbxfpsunlocker#189]
When I open it and turn on roblox (or vice versa) it still crashes !!!
plzz help i want more fps
(PS: I cant drag there any pic cause my pc is retarded af)

**Comment by CelestialVindication** [comment]
What crashes? If ROBLOX crashes, it might be some other program which effects it (free exploits usually do it because their security bypass was patched). If the program itself crashes, you may have deleted an important file like the CONFIG (i dont know if deleting the config would actually break it). Try reinstalling the program.

**Comment by axstin** [comment]
Combining with issue #190
