### ISSUE TITLE
new update 1/27/2020

### ISSUE THREAD

**Issue by robloxgamer1025** [axstin/rbxfpsunlocker#192]
there's a new update in Roblox so could you please update the Roblox FPS Unlocker as soon as possible please? Very much appreciated! :)

**Comment by balldoowell** [comment]
The latest release still seems to be working for me as of 1/29

**Comment by totallylostandconfused** [comment]
a friend recommended roblox fps unlocker and its not working. so my question is could it be my graphics card. mines pretty old. like whats the oldest graphics card it can run on if thats even the issue. i downloaded the program. i extracted the files. i ran a game, ran the program. (i tried that vise versa as well) and setting an fps limit and choosing to load the settings does nothing. my fps does not go higher than 30 and i set the limit to 60. since thats the highest refresh rate my monitor has. and idk what im doing wrong.

**Comment by Hexcede** [comment]
> a friend recommended roblox fps unlocker and its not working. so my question is could it be my graphics card. mines pretty old. like whats the oldest graphics card it can run on if thats even the issue. i downloaded the program. i extracted the files. i ran a game, ran the program. (i tried that vise versa as well) and setting an fps limit and choosing to load the settings does nothing. my fps does not go higher than 30 and i set the limit to 60. since thats the highest refresh rate my monitor has. and idk what im doing wrong.

This probably isn't your graphics card I'm guessing as FPS unlocker only changes the rate that Roblox limits your FPS to (which doesn't rely on the GPU at all). What do you see in the console? (Taskbar icon > Show console) Do you normally get under 60 fps? If the last question is a yes, than you might just not be able to run the game that fast either because your CPU is not fast enough or your GPU is not fast enough (old integrated graphics tend to perform poorly since graphics are run on the CPU).

Here are some tips which may improve performance with your game: Open Task Manager and find Roblox. Right click it and click show details. It will bring you to a new tab named details and you'll have RobloxPlayerBeta selected. If you right click it there will be an option named "Set Affinity" which allows you to pick which cores the game can run at. Overall high CPU programs on the first core (probably shown as "Core 0") will slow down the whole OS and very negatively effect performance overall so disabling Core 0 may improve your stability in game.

Secondly you can use Set Performance and set it to Realtime (I'd recommend not doing this if you leave Core 0 on as it will heavily slow down Windows). This will basically give Roblox's CPU usage a higher priority meaning it can use CPU faster than other programs on the same cores. 

If you're looking for a cheap desktop GPU I'd really recommend the AMD Radeon RX 570 GPU as its currently very cheap (~$100) and actually very performant. It also still is fully supported by AMD which is a big plus since you get the latest drivers.

AMD Ryzen CPUs are also pretty cheap and performant if you have an AMD motherboard. (Note that Intel CPUs don't work in AMD motherboards and AMD CPUs likewise don't work in Intel motherboards. GPUs however don't work this way)
