### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 666fufu** [axstin/rbxfpsunlocker#193]
my unblocker isn't working anymore i tried to restart my pc but it doesn't seem to work.

**Comment by DeztinalGamer** [comment]
O meu unlocker não está funcionando e eu fiz todo o procedimento

**Comment by Hexcede** [comment]
Please be more specific on what you mean by "not working". Usually if you have an issue with something details are really important for people to find the issues you're talking about. The more information we have about the issue, the easier we can find the issue because we know where to look and what to try doing. Do you get an error message? Does nothing happen? What does the console output of the program say? (Taskbar Icon > Toggle Console) What is your cap setting set to?

**Comment by 666fufu** [comment]
![image](https://user-images.githubusercontent.com/60527191/74037939-54ca9380-498d-11ea-8685-eb580dd38ae2.png)

**Comment by 666fufu** [comment]
i have my cap at 240fps and it only go to 60 i tried changing the cap it doesn't seem to work i even tried to redownload the program.

**Comment by 666fufu** [comment]
and if you want to see what the console say dm on discord i dont want to leak something my discord is oli#6703

**Comment by lr-hextar** [comment]
@666fufu what kind of graphics card you got?

**Comment by 666fufu** [comment]
ok i just did all the step thanks

**Comment by 666fufu** [comment]
oh wait it doesn't seem to work

**Comment by 666fufu** [comment]
it's still stuck at 60fps

**Comment by 666fufu** [comment]
i think its because the console say this
![image](https://user-images.githubusercontent.com/60527191/74094219-98b3ba80-4aab-11ea-96c4-a1025be1a122.png)

**Comment by axstin** [comment]
Does this still occur with the latest version? If so, please screenshot your RFU console output after joining a game and post it here.

**Comment by NoahHere** [comment]
![Anteckning 2020-02-22 184030](https://user-images.githubusercontent.com/61352852/75096760-fe6f6e80-55a2-11ea-9b58-14881891a022.png)
Still happens as you can see here.

**Comment by 666fufu** [comment]
i downloaded the new version and it still doesn't seem to work. Here's what my console say
![image](https://user-images.githubusercontent.com/60527191/75293120-8481f400-57f3-11ea-8a92-eaf3704f2fb0.png)

**Comment by 666fufu** [comment]
im sorry for the lack of response

**Comment by Hexcede** [comment]
@666fufu You need to set the cap first. On your task bar select "Show hidden icons" in the bottom right. Then right click on FPS unlocker's icon, hover over FPS Cap, and select the cap you want. Alternatively you can edit the `settings` file in notepad to have any cap you want (don't go too high or it'll crash Roblox unfortunately. 240 is a reasonable cap though).

**Comment by 666fufu** [comment]
yes i already know that the cap is 240

**Comment by NoahHere** [comment]
@Hexcede I've also set my cap at 240, but it still doesn't seem to work... Sometimes it says the variable scan failed too. What can be the cause of that?

**Comment by Kamciogamingyt** [comment]
It also doesn't work for me. When I turn on this application, roblox closes after switching it on again, it doesn't unlock my fps

**Comment by Hexcede** [comment]
@NoahHere @666fufu What's the refresh rate of your monitor and what type of GPU do you have? (Intel/AMD/Nvidia) This may be due to VSync, so you should try disabling VSync.

Additionally you're not getting any errors in the console correct? It could just be that your game is running at 60 FPS because your GPU just can't go any higher. Try using FPS unlocker in an empty baseplate place and see if you can get above 60. If so, it most likely means the place you're trying to use it in is too resource intensive.

**Comment by 666fufu** [comment]
i already disabeled the vsync on Nvidia and it does nothing. Here is what it says: 
![image](https://user-images.githubusercontent.com/60527191/75899784-f963b800-5e09-11ea-95e0-e67866f53f34.png)

**Comment by PhoenixShay** [comment]
please try the 32bit version of fps unlocker

**Comment by Maks7594** [comment]
How does the fps cap work? Does it freeze the FPS at the fps cap? Does it not allow to go past the fps cap?

**Comment by Hexcede** [comment]
> How does the fps cap work? Does it freeze the FPS at the fps cap? Does it not allow to go past the fps cap?
The game likely simply measures the time it took to render one frame, then, if that time is less than `1/fpsCap`, it waits long enough for it to reach `1/fpsCap`. At least, this is a *very* common way to limit FPS (Minecraft uses this method). Effectively, the game will simply slow down each frame if its too short.

(P.s. this is likely also why a cap of 0 or a very small cap value causes a freeze since 1/0 is not a number, and if I had to guess the reason for high cap values freezing the game may be due to a numeric overflow)

**Comment by Maks7594** [comment]
Thanks, I kept my FPS cap at 75, and it gives me 60 FPS.

śr., 14 paź 2020 o 22:02 Hexcede <notifications@github.com> napisał(a):
