### ISSUE TITLE
Occasional frame drops.

### ISSUE THREAD

**Issue by timthesmallbowl** [axstin/rbxfpsunlocker#1931]
was playing Phantom Forces, I set the cap to 240. Yet, it was dropping to around 40 - 50 fps approx.

**Comment by InternalBrosOfficial** [comment]
Same happens to me too. Just try deleting textures and that should work. If in arsenal delete textures and turn off shadows. You can also turn off the other settings. Happy new year!! If you need a video of this ask me!

**Comment by LucasMZReal** [comment]
That's because with a frame limiter, your computer doesn't NEED to render those frames. If you're getting frame drops, and you are already not getting 60 fps at all, dont use it, you can use it to disable v-sync, but you should limit it to 60 or so.

This isn't really a issue with the program, more than a problem with your computer.

And don't delete textures, it's dumb. Doesn't even improve performance most of the cases.

**Comment by axstin** [comment]
See FAQ.
