### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by sylvxeon** [axstin/rbxfpsunlocker#194]
this is isnt really a issue but will there ever be a mac version for this because im poor and cant afford a new pc

**Comment by TableFlipper2** [comment]
First off if you havea  fucking brain, c++ doesnt work on MAC: 2) NO

**Comment by Hexcede** [comment]
Read the FAQ. Number 5 has the answer to this request. It links here: https://github.com/axstin/rbxfpsunlocker/issues/49

> Reply by **axstin**, the developer:
I currently do not have a Mac to test on nor have I ever developed software for MacOS. RFU relies heavily on Windows API; setting up a Mac dev environment and porting the project is a task I don't have the time (or motivation) for. Closing this issue for now.

And yes, @TableFlipper2, C++ does work on a Mac, in fact it even has a compiler built into the OS. So you are the one with no brain :wink:. The first two results on Google for "Does c++ work on mac" and "Does c plus plus work on mac" show you this:
https://stackoverflow.com/questions/21733019/how-to-write-c-on-mac
https://stackoverflow.com/questions/33007724/can-a-c-program-run-on-mac-os

**Comment by TableFlipper2** [comment]
... macs cant even display over 60hz in the first place

**Comment by Hexcede** [comment]
@TableFlipper2 
The 2019 Macbook Pro's screen has a refresh rate of 60hz, so does the four thousand dollar Mac Pro, HOWEVER, you could, for example, use a 120hz monitor if you wanted. 

Here's a Youtube video demonstrating exactly this: https://www.youtube.com/watch?v=oHCtS5lkKjY
Comments state you can even get 144hz monitor working with 10-15 USD adapters.

I too hate Mac, simply because of their business standards, but this suggestion is a completely valid one to make.
