### ISSUE TITLE
Anti malware says 3.0 has trojan

### ISSUE THREAD

**Issue by beltimas** [axstin/rbxfpsunlocker#22]
dont know why a file in it would be named trojan so im a little bit sketched

**Comment by beltimas** [comment]
nevermind this stopped happening after i wrote this

**Comment by beltimas** [comment]
i decided to download it and now Cox is saying that one of my house's computers has trojan. 
"False positive"

**Comment by How-Bout-No** [comment]
I'm fairly certain it has to do with the way the injector works, which can mislead some antivirus programs

**Comment by beltimas** [comment]
maybe
but now either im nervous or my computer is slower

**Comment by ElementTimes682** [comment]
It could be because it just looks for the roblox processes, the VirusTotal link is here, it seems to give 14 false positives out of those 66 AVs. https://www.virustotal.com/#/file/a7c6554051d592bf666d0ad5781d0bcbeb632d61aa92d9df889d8a1443f7b661/detection

It works for me, If you are still worried, I don't think you can loom into the files yourself and compile something unless you want to ask axstin.

**Comment by PhoenixShay** [comment]
you're welcomed to compile on your own if you don't trust the releases
