### ISSUE TITLE
When opening the FPSUnlocker. Cannot connect to GitHub problem. 

### ISSUE THREAD

**Issue by KeysandLemons** [axstin/rbxfpsunlocker#62]
Also, It wont show any of the coding. Help

**Comment by axstin** [comment]
This error means RFU couldn't connect to GitHub to check for updates. This could be because you are not connected to the internet, GitHub is down, or your firewall is blocking RFU.

The error can be safely ignored (press OK) and the unlocker will still function, although you will need to manually check for updates.
