### ISSUE TITLE
FPS not increasing

### ISSUE THREAD

**Issue by PRIC3L3SS** [axstin/rbxfpsunlocker#7]
I ran this program (because my fps is at 20 on average) and then it did nothing, my FPS are still jumping between 10 - 30

**Comment by axstin** [comment]
This program only removes the 60 fps limit Roblox has in place. It does not boost your fps or increase performance in any way.

**Comment by PRIC3L3SS** [comment]
Aw :/

how did you even get up 800 FPS when my max is 37

**Comment by TominoCZ** [comment]
By the way.. I would contact the ROBLOX developers directly about this if I were you.. I think they would allow it. I'm not sure if this 'hack' somehow fixes the in-game bug with the physics because I know that some similar 'hacks' used to mess up the physics because it's tied to the frame rate but if this 'hack' does actually fix it then I think you should show this to the ROBLOX devs. Just sayin'

**Comment by Pokl1** [comment]
ROBLOX needs Occlusion Culling.  genuinely the rendering technique needs a recede in general, I find myself looking at different areas and they're rendering more than they should with my current "graphics level" ROBLOX provides.
